# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0a63a73b4cc07a21c6053601d5eb491"
application_url = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/shopify/install-or-render"
embedded = true
name = "Fractions App"
handle = "fractions-app"

[build]
dev_store_url = "quickstart-b6a50718.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  uri = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/webhooks/shopify"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[auth]
redirect_urls = [
  "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/connections/auth/shopify/callback"
]

[pos]
embedded = false
