name = "Fractions App"
client_id = "d0a63a73b4cc07a21c6053601d5eb491"
application_url = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/shopify/install-or-render"
embedded = true
handle = "fractions-app"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = """
unauthenticated_read_product_tags,
unauthenticated_read_product_listings,
unauthenticated_read_product_inventory,
unauthenticated_read_metaobjects,
unauthenticated_read_checkouts,
unauthenticated_write_checkouts,
read_validations,
write_validations,
read_themes,
write_themes,
read_script_tags,
write_script_tags,
read_product_listings,
read_order_edits,
write_order_edits,
read_metaobjects,
write_metaobjects,
read_metaobject_definitions,
write_metaobject_definitions,
read_locations,
read_inventory,
write_inventory,
read_draft_orders,
write_draft_orders,
read_cart_transforms,
read_audit_events,
read_products,
write_products,
read_fulfillments,
write_orders,
read_orders,
read_checkouts,
read_online_store_pages,
write_checkouts
"""

[auth]
redirect_urls = ["https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [
  "app/scopes_update",
  "app/uninstalled",
  "app_purchases_one_time/update",
  "app_subscriptions/update",
  "bulk_operations/finish",
  "carts/create",
  "carts/update",
  "domains/create",
  "domains/destroy",
  "domains/update",
  "draft_orders/create",
  "draft_orders/delete",
  "draft_orders/update",
  "fulfillment_events/create",
  "fulfillment_events/delete",
  "inventory_items/create",
  "inventory_items/delete",
  "inventory_items/update",
  "inventory_levels/connect",
  "inventory_levels/disconnect",
  "inventory_levels/update",
  "order_transactions/create",
  "orders/cancelled",
  "orders/edited",
  "orders/fulfilled",
  "orders/partially_fulfilled",
  "orders/shopify_protect_eligibility_changed",
  "product_feeds/create",
  "product_feeds/update",
  "product_listings/add",
  "product_listings/remove",
  "product_listings/update",
  "products/create",
  "products/delete",
  "products/update",
  "returns/cancel",
  "returns/close",
  "returns/reopen",
  "shop/update",
  "themes/create",
  "themes/delete",
  "themes/publish",
  "themes/update",
  "variants/in_stock",
  "variants/out_of_stock"
  ]
  uri = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/webhooks"
  api_version = "2024-10"

  [[webhooks.subscriptions]]
  topic = "metaobjects/create"
  filter = "namespace:basic_fabric AND key:basic_fabric"
  uri = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/webhooks/metaobject-create"
  api_version = "2024-10"

  [[webhooks.subscriptions]]
  topic = "metaobjects/update"
  filter = "namespace:basic_fabric AND key:basic_fabric"
  uri = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/webhooks/metaobject-update"
  api_version = "2024-10"

  [[webhooks.subscriptions]]
  topic = "metaobjects/delete"
  filter = "namespace:basic_fabric AND key:basic_fabric"
  uri = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/webhooks/metaobject-delete"
  api_version = "2024-10"

[webhooks.privacy_compliance]
customer_deletion_url = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/webhooks/shopify"
customer_data_request_url = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/webhooks/shopify"
shop_deletion_url = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/webhooks/shopify"

[pos]
embedded = false

[build]
dev_store_url = "quickstart-b6a50718.myshopify.com"
include_config_on_deploy = true
update_urls = "https://fractional-quantities-app-production-copy--dev-only.gadget.app/api/shopify/update"