# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Fractional Quantities App"
client_id = "b0f24e4a1f57de5988006853622cf678"
application_url = "https://shopify-app-theme-extension-gamma.vercel.app/shopify/api/shopify/install-or-render"
embedded = true
handle = "fractional-quantities-app"

[access_scopes]
scopes = "unauthenticated_read_product_tags,
unauthenticated_read_product_listings,
unauthenticated_read_product_inventory,
unauthenticated_read_metaobjects,
unauthenticated_read_checkouts,
unauthenticated_write_checkouts,
read_validations,
write_validations,
read_themes,
write_themes,
read_script_tags,
write_script_tags,
read_product_listings,
read_order_edits,
write_order_edits,
read_metaobjects,
write_metaobjects,
read_metaobject_definitions,
write_metaobject_definitions,
read_locations,
read_inventory,
write_inventory,
read_draft_orders,
write_draft_orders,
read_cart_transforms,
read_audit_events,
read_products,
write_products,
read_fulfillments,
write_orders,
read_orders,
read_checkouts,
write_checkouts"

[auth]
redirect_urls = [
  "https://shopify-app-theme-extension-gamma.vercel.app/shopify/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://shopify-app-theme-extension-gamma.vercel.app/shopify/api/webhooks/shopify"
  customer_data_request_url = "https://shopify-app-theme-extension-gamma.vercel.app/shopify/api/webhooks/shopify"
  shop_deletion_url = "https://shopify-app-theme-extension-gamma.vercel.app/shopify/api/webhooks/shopify"

[pos]
embedded = false
